sudo: required
services:
        - docker

before_install:
        - docker build -t kracklabs/docker-stuff -f Dockerfile.dev .

script:
        - docker run -e CI=true kracklabs/docker-stuff npm run test

deploy:
        provider: elasticbeanstalk
        region: "us-west-2"
        app: "someapp"
        env: "someapp-env"
        bucket_name: "elasticbeanstalk-us-west-2-959206288261"
        bucket_path: "someapp"
        on:
                branch: master
        access_key_id: $access_key_id
        secret_access_key: $secret_access_key
