sudo: required
services:
        - docker

before_install:
        - docker build -t kracklabs/docker-stuff -f Dockerfile.dev .

script:
        - docker run -e CI=true kracklabs/docker-stuff npm run test
